# Generated by Django 3.2.3 on 2021-06-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_alter_events_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_user',
        ),
    ]
